#############################################################################
# Makefile for building: asyncfb
# Generated by qmake (2.01a) (Qt 4.4.0-rc1) on: Sun Sep 28 20:59:13 2008
# Project:  asyncfb.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile asyncfb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DIBPP_LINUX -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lfbclient -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/database.cpp \
		src/database_p.cpp \
		src/sqlview.cpp \
		src/private/ibpp/core/all_in_one.cpp moc_main.cpp \
		moc_database.cpp \
		moc_database_p.cpp \
		moc_sqlview.cpp
OBJECTS       = main.o \
		database.o \
		database_p.o \
		sqlview.o \
		all_in_one.o \
		moc_main.o \
		moc_database.o \
		moc_database_p.o \
		moc_sqlview.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		asyncfb.pro
QMAKE_TARGET  = asyncfb
DESTDIR       = 
TARGET        = asyncfb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: asyncfb.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile asyncfb.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile asyncfb.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/asyncfb1.0.0 || $(MKDIR) .tmp/asyncfb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/asyncfb1.0.0/ && $(COPY_FILE) --parents src/main.h src/database.h src/database_p.h src/sqlview.h .tmp/asyncfb1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/database.cpp src/database_p.cpp src/sqlview.cpp src/private/ibpp/core/all_in_one.cpp .tmp/asyncfb1.0.0/ && (cd `dirname .tmp/asyncfb1.0.0` && $(TAR) asyncfb1.0.0.tar asyncfb1.0.0 && $(COMPRESS) asyncfb1.0.0.tar) && $(MOVE) `dirname .tmp/asyncfb1.0.0`/asyncfb1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/asyncfb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp moc_database.cpp moc_database_p.cpp moc_sqlview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp moc_database.cpp moc_database_p.cpp moc_sqlview.cpp
moc_main.cpp: src/database.h \
		src/sqlview.h \
		src/main.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/main.h -o moc_main.cpp

moc_database.cpp: src/database.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/database.h -o moc_database.cpp

moc_database_p.cpp: src/database.h \
		src/database_p.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/database_p.h -o moc_database_p.cpp

moc_sqlview.cpp: src/database.h \
		src/sqlview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/sqlview.h -o moc_sqlview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/main.h \
		src/database.h \
		src/sqlview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

database.o: src/database.cpp src/database.h \
		src/database_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/database.cpp

database_p.o: src/database_p.cpp src/private/ibpp/core/ibpp.h \
		src/main.h \
		src/database.h \
		src/sqlview.h \
		src/database_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database_p.o src/database_p.cpp

sqlview.o: src/sqlview.cpp src/sqlview.h \
		src/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlview.o src/sqlview.cpp

all_in_one.o: src/private/ibpp/core/all_in_one.cpp src/private/ibpp/core/_ibpp.cpp \
		src/private/ibpp/core/_ibpp.h \
		src/private/ibpp/core/ibpp.h \
		src/private/ibpp/core/ibase.h \
		src/private/ibpp/core/iberror.h \
		src/private/ibpp/core/_dpb.cpp \
		src/private/ibpp/core/_ibs.cpp \
		src/private/ibpp/core/_rb.cpp \
		src/private/ibpp/core/_spb.cpp \
		src/private/ibpp/core/_tpb.cpp \
		src/private/ibpp/core/array.cpp \
		src/private/ibpp/core/blob.cpp \
		src/private/ibpp/core/database.cpp \
		src/private/ibpp/core/date.cpp \
		src/private/ibpp/core/dbkey.cpp \
		src/private/ibpp/core/events.cpp \
		src/private/ibpp/core/exception.cpp \
		src/private/ibpp/core/row.cpp \
		src/private/ibpp/core/service.cpp \
		src/private/ibpp/core/statement.cpp \
		src/private/ibpp/core/time.cpp \
		src/private/ibpp/core/transaction.cpp \
		src/private/ibpp/core/user.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o all_in_one.o src/private/ibpp/core/all_in_one.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_database_p.o: moc_database_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database_p.o moc_database_p.cpp

moc_sqlview.o: moc_sqlview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sqlview.o moc_sqlview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

